freebsd_instance:
  image_family: freebsd-14-2

task:
  install_script: pkg install -y ghc hs-cabal-install git
  script:
    - ghc --version
    - cabal --version
    - cabal update
    - cabal test --test-show-details=direct --enable-tests
    - cabal test -f-simd --test-show-details=direct --enable-tests
