name: ci
on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  build-freebsd:
    # https://github.com/vmactions/freebsd-vm#under-the-hood.
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      id: build-FreeBSD
      uses: vmactions/freebsd-vm@v0.0.9
      with:
        usesh: true
        prepare: pkg install -y ghc hs-cabal-install autoconf git
        run: |
          cabal update
          cabal test -flibgmp
          cabal test
          cabal bench --benchmark-option=-l
          cabal haddock
          cabal sdist

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]
        ghc: ['8.10', '8.8.4', '8.8.2', '8.8.1', '8.6', '8.4', '8.2', '8.0']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      id: setup-haskell-cabal
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: 'latest'
    - uses: actions/cache@v2
      name: Cache cabal stuff
      with:
        path: |
          ${{ steps.setup-haskell-cabal.outputs.cabal-store }}
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc }}-${{ hashFiles('cabal.project.freeze') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ghc }}-
    - name: Build
      run: |
        cabal test -flibgmp
        cabal test
        cabal bench --benchmark-option=-l
        cabal haddock
        cabal sdist
